export const styles = {
    appContainer:  {
        textDecoration: 'none',
        display: 'flex',
        alignItems: 'center',
        height: '100%',
        width: '100%',
        position: 'relative',
        flexDirection: 'row',
        gap: '20px',
        // padding: '20px 30px 30px 30px',
        padding: '10px 10px 10px 10px',
        userSelect: 'none',
        color: 'rgb(0, 0, 0)',
        maxWidth: '100%',
        textAlign: 'left',
        maxHeight: '100px',
        overFlow: 'hidden',
        border: '1px solid red',
        cursor: 'pointer', 
        justifyContent: 'flex-start',
        transform: 'scale(0.8)'
    },
    columnContainer:  {
        textDecoration: 'none',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
        position: 'relative',
        flexDirection: 'column',
        gap: '8px',
        padding: '20px 30px 30px 30px',
        userSelect: 'none',
        color: 'rgb(0, 0, 0)',
        // maxWidth: '80%',
        // margin: 'auto',
        // maxHeight: '150px',
        // maxWidth: '170px',
        maxWidth: '200px',
        // maxWidth: '500px',
        maxHeight: '150px',
        overFlow: 'hidden',
        border: '1px solid transparent',
        cursor: 'pointer',
        margin: '15px auto'
    },
    img: {
        width: '110px',
        height: '110px',
        position: 'relative',
        borderRadius: '11px'
    },
    title: {
        fontSize: '14px',
        marginTop: '5px',
        textTransform: 'capitalize',
        display: 'flex',
    },
    flexedRow: {
        // display: 'flex',
        padding: '10px 30px',
        // margin: '10px',
        // justifyContent: 'space-around',
        flexWrap: 'wrap',
        width: '80%',
        margin: 'auto',
        // border: '1px solid red',

        display: 'grid',
        gridTemplateColumns: '20% 20% 20% 20% 20%',
    },
    flexedColumn: {
        display: 'flex',
        flexDirection: 'column' as 'column',
        padding: '30px 30px',
        margin: '10px',
        justifyContent: 'space-around',
        // border: '1px solid red'
    },
    toolBarButton: {
        cursor: 'pointer',
        backgroundColor: 'transparent',
        border: 'none'
    }
}